# Generated by Django 4.0.8 on 2022-12-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Carreras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('codigo', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Codigo', max_length=16, primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Nombre', max_length=100)),
            ],
            options={
                'db_table': 'Cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('idgrupo', models.AutoField(db_column='idGrupo', primary_key=True, serialize=False)),
                ('horario', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='Horario', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Grupos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('idmatricula', models.AutoField(db_column='idMatricula', primary_key=True, serialize=False)),
                ('tipomatricula', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', db_column='TipoMatricula', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Matricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('idperiodo', models.AutoField(db_column='idPeriodo', primary_key=True, serialize=False)),
                ('fecha_incio', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AS', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Periodos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('identificacion', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Identificacion', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(db_collation='Modern_Spanish_CI_AS', db_column='Password', max_length=16)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
